image: golang:1.12

cache:
    paths:
        - /apt-cache
        - /go/src/golang.org
        - /go/src/gopkg.in
        - /go/src/github.com

before_script:
    - mkdir -p /go/src/gitlab.com/magsh-2019/2/gud/
    - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/magsh-2019/2/gud/
    - go get -v -d gitlab.com/magsh-2019/2/gud/gud

lib:
    stage: test
    script:
        - go test gitlab.com/magsh-2019/2/gud/gud
