image: golang:1.13

before_script:
    - pkg_name=gitlab.com/magsh-2019/2/gud
    - mkdir -p /go/src/$(dirname $pkg_name)
    - cp -r $CI_PROJECT_DIR /go/src/$pkg_name
    
    - git clone --depth=1 https://github.com/bats-core/bats-core.git
    - cd bats-core
    - ./install.sh /usr/local
    
    - cd /go/src/$pkg_name
    - make lib

lib:
    stage: test
    script:
        - GO111MODULE=off go test $pkg_name/gud
    only:
        changes:
            - gud/*

cli:
    stage: test
    script:
        - cd /go/src/$pkg_name
        - bats test.bats
