image: golang:1.12

cache:
    paths:
        - /apt-cache
        - /go/src/golang.org
        - /go/src/gopkg.in
        - /go/src/github.com

before_script:
    - mkdir -p /go/src/gitlab.com/magsh-2019/2/
    - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/magsh-2019/2/gud/

lib:
    stage: test
    script:
        - go test gitlab.com/magsh-2019/2/gud/gud
    only:
        changes:
            - gud/*

cli:
    stage: test
    before_script:
        - git clone https://github.com/bats-core/bats-core.git
        - cd bats-core
        - ./install.sh /usr/local
        - make -C /go/src/gitlab.com/magsh-2019/2/gud/ cli
    script:
        - bats /go/src/gitlab.com/magsh-2019/2/gud/test.bats
